

(function() {

mabp.localization = {};
     mabp.localization['Bpm.zh-CN'] = {
             'AppName' : '东风延锋 - 工作流系统',
             'SiteName' : '东风延锋',
             'PersonalInformation' : '个人信息',
             'AutomaticGenerationSystem' : '系统自动生成',
             'RealName' : '姓名',
             'BasicSettings' : '基本设置',
             'NickName' : '昵称',
             'ChangePassword' : '密码更改',
             'Account' : '账号',
             'OpenApi' : '开发接口',
             'Address' : '地址',
             'Language' : '语言',
             'Save' : '保存',
             'Saveing' : '保存中',
             'OrignalPassword' : '原密码',
             'NewPassword' : '新密码',
             'RepeatPassword' : '重复密码',
             'CurrentCellphone' : '当前手机号',
             'NewCellphone' : '新手机号',
             'CurrentEmail' : '当前邮箱',
             'UserAccessId' : '用户密钥',
             'EnterpriseAccessId' : '企业密钥',
             'UnbindAtLeastHaveOne' : '解除绑定，手机号邮箱必须存在一个',
             'Reset' : '重置',
             'ValidationCode' : '验证码',
             'Cancel' : '取消',
             'BindNewEmail' : '绑定新邮箱',
             'BindNewCellphone' : '绑定新手机',
             'UnBind' : '解除绑定',
             'SendValidationCode' : '发送验证码',
             'EnterNewEmail' : '输入新邮箱',
             'EnterNewCellphone' : '输入新手机号',
             'EnterValidationCode' : '输入验证码',
             'ChangeMail' : '修改邮箱',
             'ChangeCellphone' : '修改手机',
             'BindEmail' : '绑定邮箱',
             'BindCellPhone' : '绑定手机',
             'SureForBind' : '确认绑定',
             'Cellphone' : '电话',
             'JobNumber' : '工号',
             'LoginAccount' : '登录账号',
             'NotBind' : '未绑定',
             'PleaseInputValidationCode' : '请输入验证码',
             'PleaseInputNewCellphone' : '请输入新手机号',
             'UpdateSuccessfully' : '更新成功',
             'PleaseClickSendValidationCode' : '请点击发送验证码!',
             'PleaseInputNewEmail' : '请输入新邮箱!',
             'ValidationCodeSendedPleaseCheckCellphone' : '验证码已发送，请查看手机！',
             'ValidationCodeSendedPleaseCheckEmail' : '验证码已发送，请查看邮箱！',
             'ModifyPassword' : '修改密码',
             'InputAccountPassword' : '输入帐号密码',
             'ConfirmThatYouAreOperatingPleaseEnterTheCurrentAccountPasswordAndContinue' : '确认是您本人操作，请输入当前帐户密码并继续',
             'InputCurrentAccountPassword' : '输入当前帐户密码',
             'ConfirmAndContinue' : '确认并继续',
             'AddApply' : '+申请代理',
             'AddAgent' : '+审批代理',
             'AgentType' : '设置方式',
             'UseUser' : '全部代理',
             'UseJob' : '按岗位代理',
             'NoAgentYetClickUpperRightToCreate' : '还没有代理设置，请点击右上角创建!',
             'AgentList' : '代理列表',
             'WorkflowMainCategory' : '流程大类',
             'WorkflowName' : '流程名称',
             'FirstAgent' : '第一代理人',
             'SecondAgent' : '第二代理人',
             'StartDate' : '开始时间',
             'EndDate' : '结束时间',
             'WhetherValid' : '是否有效',
             'Operation' : '操作',
             'Valid' : '有效',
             'Invalid' : '无效',
             'Edit' : '编辑',
             'Create' : '创建',
             'Agent' : '代理',
             'Basic' : '基本',
             'OperationSucceeded' : '操作成功',
             'GetLatestWorkflow' : '获取最新流程',
             'NoWorkflowYetClickUpperRightToGetLatest' : '还没有流程，请点击右上角获取最新!',
             'Workflow' : '流程',
             'Name' : '名称',
             'Code' : '代码',
             'CreationDate' : '创建日期',
             'CreationTime' : '创建时间',
             'Source' : '来源',
             'Size' : '完成时间',
             'SureForDeleteThisWorkflow' : '删除此流程？',
             'CreateWorkflow' : '+创建流程',
             'NoWorkflowCategoryYetPleaseCreateFirstly' : '还没有流程分类，请先创建',
             'WorkflowCode' : '流程代码',
             'Category' : '分类',
             'Description' : '描述',
             'WorkflowDescription' : '流程描述',
             'Close' : '关闭',
             'WorkflowInfo' : '流程信息',
             'State' : '状态',
             'GetChoosedWorkflow' : '获取选中流程',
             'SynchronizedSuccess' : '同步成功',
             'Permissions' : '的权限',
             'Handler' : '处理人',
             'Launch' : '发起',
             'Check' : '查看',
             'Dispatch' : '调度',
             'Delete' : '删除',
             'Revoke' : '撤销',
             'Job' : '岗位',
             'Variable' : '变量',
             'VariableName' : '变量名',
             'VariableType' : '变量类型',
             'System' : '系统',
             'Refresh' : '刷新',
             'File' : '文件',
             'Date' : '日期',
             'Text' : '文本',
             'Number' : '数值',
             'PleaseConfirmTheDeletionAgain' : '请再次确认删除？',
             'PleaseInputVariableName' : '请填写变量名',
             'DeleteSuccessfully' : '删除成功',
             'GetTableDesign' : '获取表设计',
             'AliasName' : '别名',
             'NoTableYetClickUpperRightToGetTable' : '还没有表，请点击右上角获取表!',
             'BusinessDatatable' : '业务表',
             'Type' : '类型',
             'ViewField' : '查看字段',
             'AssociateParentTable' : '关联父表',
             'ChooseAssociatedParentTable' : '选择关联的父级表',
             'BasicDatatable' : '基础表',
             'SysDatatable' : '系统表',
             'TableMaintenance' : '表维护',
             'Common' : '常规',
             'FieldCode' : '字段代码',
             'FieldName' : '字段名称',
             'Length' : '长度',
             'Required' : '必填',
             'RequirementDescription' : '需求描述',
             'DataMaintenanceSettings' : '数据维护配置',
             'WhetherVisible' : '是否可见',
             'Alignment' : '对齐',
             'Content' : '内容',
             'Left' : '左',
             'Center' : '中',
             'Right' : '右',
             'DataQuerySettings' : '数据查询配置',
             'CanAssociate' : '可关联',
             'CanQuery' : '可查询',
             'CanSort' : '可排序',
             'CanGroup' : '可分组',
             'CanStatistics' : '可统计',
             'DatatableInfo' : '数据表信息',
             'TableName' : '表名',
             'TableDescription' : '表描述',
             'GetAllDatatable' : '获取全部数据表',
             'GetChoosedDatatable' : '获取选中数据表',
             'MainDatatable' : '主表',
             'MappingSourceTable' : '来源表/视图',
             'MappingSourceField' : '来源字段',
             'MappingDataType' : '数据类型',
             'MappingFieldFormat' : '数据格式',
             'MappingDestElement' : '匹配字段',
             'MappingParentDestElement' : '匹配父字段',
             'CreateCategory' : '+创建分类',
             'NoWorkflowCategoryYetClickUpperRightToCreate' : '还没有流程分类，请点击右上角创建!',
             'WorkflowCategory' : '流程分类',
             'ViewWorkflow' : '查看流程',
             'SureForDeleteThisCategory' : '删除此分类？',
             'WorkflowCategoryCode' : '流程分类代码',
             'Menu_My_Outing_NewApproval' : '菜单-我的-外出设置-新增审批代理',
             'Menu_My_Outing' : '菜单-我的-外出设置',
             'Menu_My_Setting' : '菜单-我的-个人设置',
             'Menu_My_Outing_NewApply' : '菜单-我的-外出设置-新增申请代理',
             'Menu_My_WorkflowCenter_AdvanceSearch' : '菜单-我的-流程中心-高级查询',
             'Menu_My' : '菜单-我的',
             'Menu_My_Workplace' : '菜单-我的-工作台',
             'Menu_My_WorkflowCenter' : '菜单-我的-流程中心',
             'Menu_My_DataMaintanance' : '菜单-我的-数据',
             'Menu_My_Report' : '菜单-我的-报表',
             'Menu_Sys' : '菜单-系统',
             'Menu_Sys_Workflow' : '菜单-系统-流程',
             'Menu_Sys_TableAndView' : '菜单-系统-表及视图',
             'Menu_Sys_Page' : '菜单-系统-页面',
             'Menu_Sys_Module' : '菜单-系统-模块',
             'Menu_Sys_Configuration' : '菜单-系统-全局配置',
             'Menu_Sys_Permission' : '菜单-系统-权限',
             'Menu_Sys_Developer' : '菜单-系统-开发者面板',
             'SysModule_Data' : '系统模块-基础数据',
             'SysModule_Data_User' : '系统模块-用户',
             'SysModule_Data_Group' : '系统模块-组织',
             'SysModule_Data_Enum' : '系统模块-枚举',
             'SysModule_Data_Role' : '系统模块-角色模块',
             'SysModule_Data_Interface' : '系统模块-接口模块',
             'SysModule_Data_BasicData' : '系统模块-基础数据集合',
             'SysModule_Data_GroupExtension' : '系统模块-公司信息',
             'Menu_My_File' : '菜单-我的-文件',
             'Permission' : '权限',
             'SysConfig' : '系统配置',
             'Perission' : '权限',
             'SyncServerAddress' : '设计器地址',
             'EnterpriseCode' : '企业代码',
             'EnterpriseName' : '企业名称',
             'MessageCenterConfiguration' : '消息中心配置',
             'MessageCenterAddress' : '消息中心地址',
             'MessageCenterAccount' : '消息中心账号',
             'MessageCenterPassword' : '消息中心密码',
             'MailServerConfiguration' : '邮件配置',
             'MailServerAddress' : '服务器地址',
             'MailServerPort' : '端口号',
             'MailServerAccount' : '账号',
             'MailServerPassword' : '密码',
             'MailServerSenderEmail' : '发送人的电子邮件',
             'MailServerSenderName' : '发送人的姓名',
             'MailServerIsSSL' : '使用SSL',
             'MailServerIsOpen' : '开启邮件',
             'FileServerConfiguration' : '文件服务器配置',
             'FileServerAddress' : 'FTP地址',
             'Username' : '用户名',
             'Password' : '密码',
             'SaveSuccessfully' : '保存成功',
             'ShowAllStep' : '显示全部',
             'Hide' : '隐藏',
             'ApplyToDatabase' : '刷到数据库',
             'GetLatest' : '获取最新',
             'GetLatestForm' : '获取最新页面',
             'NoFormYetClickUpperRightToGetLatest' : '还没有表单，请点击右上角获取最新',
             'Form' : '表单',
             'SureForDeleteThisForm' : '删除此表单？',
             'BusinessTable' : '业务表单',
             'FormType' : '表单类型',
             'FormName' : '表单名称',
             'FormDescription' : '表单描述',
             'BasicData' : '基础数据',
             'Report' : '报表',
             'FormInfo' : '表单信息',
             'GetAllForm' : '获取全部表单',
             'GetChoosedForm' : '获取选中表单',
             'EntryDetailForm' : '进入明细表',
             'MainPage' : '主页面',
             'FormMultiLanguageConfig' : '表单多语言配置',
             'FormMultiLanguageImport' : '表单多语言导入',
             'CreateModule' : '+创建模块',
             'NoModuleYetClickUpperRightToCreate' : '还没有模块，请点击右上角创建!',
             'IdentificationName' : '标识名称',
             'Open' : '开启',
             'AssociatePage' : '关联页面',
             'AssociateWorkflow' : '关联流程',
             'OpenSuccessfully' : '开启成功',
             'CloseSuccessfully' : '关闭成功',
             'Module' : '模块',
             'IdentifierPrefix' : '标识前缀',
             'Advance' : '高级',
             'ModuleAssociateForm' : '模块关联表单',
             'PageName' : '页面名称',
             'PageDescription' : '页面描述',
             'FileName' : '文件名',
             'Datatable' : '数据表',
             'SureForDelete' : '确认删除？',
             'SureSetStartPage' : '确定设为开始页？',
             'ChooseForm' : '选择表单',
             'ModuleAssociateWorkflow' : '模块关联流程',
             'SwitchWorkflow' : '切换流程',
             'ConfirmSubmitWillCoverSettedForm' : '确认提交会覆盖之前设置的表单',
             'AssociateRight' : '模块权限',
             'Allow' : '允许',
             'OpenType' : '打开方式',
             'ModuleOpenType' : '模块打开方式',
             'CreateReport' : '+创建报表',
             'NoReportYetClickUpperRightToAdd' : '还没有报表，请点击右上角添加报表!',
             'DesignReportFormat' : '设计报表格式',
             'ReportType' : '报表类型',
             'DropdownlistChoose' : '下拉选择：固定格式/图表格式/二维表格式',
             'ReportName' : '报表名称',
             'ReportDescription' : '报表描述',
             'AssociateParentReport' : '关联父报表',
             'PopupSelectionReport' : '弹出选择报表',
             'CautionDeleteWorkflowWillDeleteAllTheRelatedData' : '请注意，删除流程会删除流程对应的所有数据！',
             'FixFormatReportDesign' : '固定格式报表设计',
             'CreateDataView' : '+创建数据视图',
             'NoDataViewYetClickUpperRightToCreate' : '还没有数据视图，请点击右上角创建数据视图!',
             'DataView' : '数据视图',
             'DataViewCode' : '视图代码',
             'DataViewNameInDatatable' : '数据库中的视图名',
             'DataViewName' : '视图名称',
             'DataViewDescription' : '视图描述',
             'DataViewSQL' : '视图SQL语句',
             'SureForDeleteThisDataView' : '删除此数据视图？',
             'DataViewFieldPropertySettings' : '视图字段属性配置',
             'DataViewSearchSQL' : '视图查询SQL语句',
             'WorkflowProcessorChange' : '流程调度',
             'WorkflowIntegration' : '流程集成',
             'AddWorkflowIntegration' : '+新增接口',
             'IntegrationCode' : '接口编号',
             'IntegrationDescription' : '接口描述',
             'FunctionDescription' : '描述',
             'IntegrationMode' : '接口方式',
             'IntegrationModify' : '修改',
             'IntegrationConfig' : '配置',
             'IntegrationMapping' : '匹配',
             'IntegrationCond' : '检索条件',
             'InterfaceConfiguration' : '接口配置',
             'HandleType' : '处理类型',
             'FileFormat' : '文件格式',
             'LoopType' : '循环类型',
             'ExecutionDate' : '执行时间',
             'IntervalTimeMS' : '间隔时间(毫秒)',
             'CallbackMethod' : '回调方法',
             'AssociateDatatable' : '关联数据表',
             'ChooseAssociatedDatatable' : '选择关联的表',
             'Enable' : '启用',
             'EnableDate' : '启用时间',
             'Interface' : '接口',
             'NoServerInterfaceYetClickUpperRightToAdd' : '还没有服务器接口，请点击右上角添加!',
             'ServerConfiguration' : '服务器配置',
             'ServerAddress' : '服务器地址',
             'DeleteInterfaceSuccessfully' : '接口删除成功',
             'InterfaceFieldConfiguration' : '接口字段配置',
             'PrimaryKey' : '主键',
             'WhetherEnable' : '是否启用',
             'ResetWillDeleteCurrentFiledConfigurationAreYouSure' : '重置后会清除现有字段配置，确定吗',
             'ftpAddress' : 'ftp地址',
             'TotalQuantity' : '全量',
             'Increment' : '增量',
             'FixedTimePerDay' : '每天固定时间',
             'FixedTimeInterval' : '固定间隔时间',
             'FixedTimeOfWorkingDay' : '工作日固定时间',
             'FixedTimeIntervalOfWorkingDay' : '工作日固定时间间隔',
             'FileServerType' : '文件服务器类型',
             'IntegrationFileServerAddress' : '服务器地址',
             'FileServerAccount' : '用户名',
             'FileServerPassword' : '密码',
             'FileServerPort' : '端口',
             'FileServerFolder' : '目录',
             'FileReturnFolder' : '返回目录',
             'FileContentMapping' : '文件内容匹配关系',
             'FileNameFormat' : '文件名格式',
             'FileExtension' : '文件后缀',
             'FileSeparator' : '分隔符',
             'SuccessCallBack' : '成功回调作业编号',
             'ErrorCallBack' : '失败回调作业编号',
             'SourceIdentifier' : '来源标识',
             'Downloads' : '下载次数',
             'WaitingDownload' : '等待下载',
             'Download' : '下载',
             'DataBaseServerType' : '中间库类型',
             'DataBaseServerAddress' : '服务器地址',
             'DataBaseAccount' : '用户名',
             'DataBasePassword' : '密码',
             'DataBaseTableName' : '表名',
             'DataBaseFieldMapping' : '字段匹配关系',
             'WebServiceUrl' : 'WebService地址',
             'WebServiceAccount' : '用户名',
             'WebServicePassword' : '密码',
             'WebServiceRootName' : '父节点',
             'WebServiceElementMapping' : '元素匹配关系',
             'UploadIntegrationFile' : '上传接口文件',
             'RereadWebservice' : '读取WebService',
             'ReadMapping' : '读取匹配',
             'SourceTable' : '来源表名',
             'SourceField' : '来源字段',
             'DestElement' : '目的节点/字段',
             'FieldDataType' : '字段类型',
             'ParentDestElement' : '目的父节点/表名',
             'MappingMemo' : '备注',
             'Undefined' : '未定义',
             'Mine' : '我的',
             'Dashboard' : '工作台',
             'WorkflowCenter' : '流程中心',
             'DataMaintenance' : '数据维护',
             'DataReport' : '数据报表',
             'WorkflowConfiguration' : '流程',
             'DatatableConfiguration' : '表及视图',
             'DataViewConfiguration' : '数据视图',
             'ReportConfiguration' : '报表',
             'FormConfiguration' : '页面',
             'Configuration' : '全局配置',
             'PersonalSettings' : '个人设置',
             'OutSettings' : '外出设置',
             'Logout' : '退出',
             'Developer' : '开发者面板',
             'TaskStatus_0' : '审批中',
             'TaskStatus_1' : '已完成',
             'TaskStatus_7' : '被拒绝',
             'TaskNumber' : '任务号',
             'Topic' : '主题',
             'Sn' : '单号',
             'Creator' : '创建人',
             'AnAgent' : '代理人',
             'Authorizer' : '授权人',
             'UnReceived' : '尚未到达',
             'ReceiveDate' : '接收时间',
             'CompletionTime' : '完成时间',
             'TaskFinishStatus' : '审批完成',
             'TaskCanceled' : '申请已取消',
             'Approving' : '审批中',
             'TaskRejectStatus' : '拒绝',
             'PendingPurchase' : '待采购',
             'AlreadyPurchase' : '已采购',
             'Refused' : '已拒绝',
             'WorkflowType' : '流程类型',
             'Company' : '所属公司',
             'CC' : '抄送人',
             'CCDate' : '抄送时间',
             'CurrentStatus' : '当前状态',
             'CurrentNode' : '当前节点',
             'CurrentHandler' : '当前处理人',
             'ModificationDate' : '修改时间',
             'ProcessingNode' : '处理节点',
             'OtherHandler' : '其它处理人',
             'CommonWorkflow' : '常用流程',
             'CollectionWorkflow' : '收藏流程',
             'AddToCommonWorkflowSuccessfullyUpToMax' : '收藏已达到上限',
             'AddToCommonWorkflowSuccessfully' : '添加收藏',
             'RemoveFromCommonWorkflowSuccessfully' : '移除成功',
             'WorkflowHandle' : '流程处理',
             'Count' : '条数',
             'Clear' : '清空',
             'WfBusinessData' : '业务数据',
             'NewWindow' : '新窗口',
             'Embedded' : '内嵌窗口',
             'Inherit' : '继承',
             'NoProcess' : '尚未添加常用流程',
             'JumpWorkflowCenter' : '点击跳转至流程页面',
             'ClickRightCorner' : '点击流程右上角☆即可标记',
             'Notasks' : '当前没有待办流程',
             'Initiated' : '发起了',
             'more' : '查看更多',
             'Nolaunchtask' : '当前没有发起流程',
             'NewTask' : '发起新流程',
             'TaskApproval' : '审批意见',
             'QueryCriteria' : '过滤条件',
             'Search' : '搜索',
             'LaunchWorkflow' : '发起流程',
             'MyPendingHandleWf' : '待办流程',
             'MyPendingReadWf' : '待阅流程',
             'WfSearch' : '流程查询',
             'MyMarkedWf' : '我标记的流程',
             'MyDraftWf' : '我草拟的流程',
             'MyRaisedWf' : '我发起的流程',
             'MyHanldeWf' : '我处理的流程',
             'MyWaitingWf' : '我挂起的流程',
             'CopyMeWf' : '抄送我的流程',
             'MyAuthorizedWf' : '我授权的流程',
             'MyDelegateWf' : '我代理的流程',
             'WfAdvancedSearch' : '流程高级查询',
             'SelectTask' : '选择流程',
             'Notaskwating' : '没有等待处理的任务',
             'NoMarked' : '当前没有标记的流程',
             'NoDraft' : '当前没有草拟的流程',
             'Nohandled' : '当前没有已处理的流程',
             'NoWaited' : '当前没有挂起的流程',
             'NoCopied' : '当前没有抄送的流程',
             'NoAuthorized' : '当前没有授权的流程',
             'NoDelegated' : '当前没有代理的流程',
             'EnumCollection' : '枚举集',
             'EnumKey' : '枚举键',
             'EnumValue' : '枚举值',
             'AddCreate' : '+新增',
             'PleaseInputName' : '请输入名称',
             'Value' : '值',
             'GroupLevel' : '组织级别',
             'GroupType' : '组织类型',
             'JobLevel' : '岗位级别',
             'JobLevel>=' : '岗位级别 >=',
             'JobLevel<=' : '岗位级别 <=',
             'JobLevel=' : '岗位级别 =',
             'NameCannotBeNull' : '名称不能为空',
             'ValueCannotBeNull' : '值不能为空',
             'GroupStructure' : '组织结构',
             'BindSuccessfully' : '绑定成功',
             'UnBindSuccessfully' : '解除绑定成功',
             'Group' : '组织',
             'ChineseName' : '中文名',
             'EnglishName' : '英文名',
             'JobBindGroup' : '岗位绑定组织',
             'BindGroup' : '绑定组织',
             'PleaseChooseGroup' : '请选择组织',
             'Confirm' : '确定',
             'TransferJob' : '转移岗位',
             'To' : '至',
             'JobUser' : '岗位人员',
             'ChooseOneJobAtLeast' : '至少选择一个岗位',
             'WhetherToMoveTheChildJobTogether' : '是否将子岗位一并移动。点击[取消]仅移动当前岗位。',
             'JobChange' : '岗位调整',
             'ChildGroup' : '子组织',
             'GroupName' : '组织名称',
             'GroupCode' : '组织代码',
             'CancelGroupAndTransforToJob' : '取消组织并转换为岗位',
             'TransforToJob' : '转为岗位',
             'TransforToJobGroupWillBeDeletedJobKeep' : '转换为岗位后，组织信息会被删除，岗位会保留',
             'DeleteThisJobAndGroupWillBeDeleted' : '删除此岗位, 将同时删除组织',
             'IfWannaRemovingBindBetweenGroupAndJobGoToGroupChart' : '若要解除组织和岗位的绑定请至组织图中',
             'UnBindFunction' : '[解除绑定]功能',
             'JobName' : '岗位名称',
             'User' : '用户',
             'JobTransforToGroup' : '岗位转换成组织',
             'TransforToGroup' : '转换为组织',
             'DeleteThisJobIfChildNodeExistThenCannotDelete' : '删除此岗位, 若存在子节点则不允许删除',
             'PleaseInputNewGroupName' : '请填写新组织名称',
             'DisplayOrder' : '排序号',
             'MultipleLanguageConfiguration' : '多语言配置',
             'DeleteUserSuccessfully' : '用户删除成功',
             'SystemEnumeration' : '系统枚举',
             'InterfaceConfig' : '接口',
             'BasicDataConfig' : '基础数据集',
             'BasicDataImport' : '基础数据导入',
             'Role' : '角色',
             'RoleJob' : '角色岗位',
             'RootRole' : '根角色',
             'ChooseARoleFirstly' : '请选择一个角色先',
             'RoleJobArea' : '负责区域',
             'RoleJobMemo' : '备注',
             'AddUser' : '添加用户',
             'NoUserYetClickUpperRightToAdd' : '还没有项目成员，请点击右上角添加',
             'EnterpriseUser' : '企业用户',
             'Email' : '邮箱',
             'GroupExtension' : '公司信息',
             'GroupExtensionCompany' : '公司名称',
             'AreaCode' : '公司代码',
             'Fax' : '传真',
             'GroupExtensionMemo' : '备注',
             'FilterCondition' : '过滤条件',
             'ShaluWorkflowDesigner' : '沙鲁流程设计器',
             'AllChangesHaveBeenSaved' : '所有更改已保存',
             'SavingData' : '正在保存数据...',
             'accessCondition' : '准入条件',
             'Button' : '按钮',
             'CorrespondingEvent' : '对应事件',
             'JumpNode' : '跳转节点',
             'SetVariable' : '设置变量',
             'Action' : '动作',
             'StateHasBeenSaved' : '状态已保存',
             'MultiLanguageHasBeenSaved' : '多语言已保存',
             'EndNode_EventCompleted' : '通过',
             'EndNode_EventRejected' : '拒绝',
             'EndNode_EventCanceled' : '取消',
             'CommandType' : '命令类型',
             'CommandText' : '命令文本',
             'CCTarget' : '抄送对象',
             'EnableCheck' : '启用考核',
             'StandardProcessingTime' : '标准处理时间',
             'NodeCode' : '节点代码',
             'PleaseInputNodeCode' : '请输入节点代码',
             'NodeName' : '节点名称',
             'NodeDescription' : '节点描述',
             'PleaseInputNodeDescription' : '请输入节点描述',
             'Mode' : '方式',
             'TheRecipient' : '接收人',
             'Format' : '格式',
             'Notice' : '通知',
             'PleaseChooseTheFollowingJumpWay' : '请选择以下跳过方式',
             'HandlerSameWithSubmitterThenSkip' : '处理人与提交人相同跳过',
             'SameWithPreviousNodeHandlerThenSkip' : '与前置节点处理人相同跳过',
             'SameWithCertainNodeHandlerThenSkip' : '与某一节点处理人相同跳过',
             'PleaseChoose' : '请选择',
             'SameWithAnyPreviousNodeHandlerThenSkip' : '与前面任意节点处理人相同跳过',
             'NoNodeHandlerThenSkip' : '无对应处理人跳过',
             'OutdatedNotice' : '过时通知',
             'HourStartEvery' : '小时开始，每隔',
             'Hour' : '小时',
             'SendNotificationToFollowingPerson' : '将给下列人员发送通知',
             'OutdatedHandle' : '过时处理',
             'Exceed' : '超过',
             'HourLater' : '小时后',
             'AutomaticallyToTheNextStep' : '自动到下一步',
             'AutomaticTransferLeadership' : '自动转领导',
             'FixedOptions' : '固定选项',
             'PretreatmentPerson' : '预处理人',
             'SingleSelect' : '单选',
             'MultiSelect' : '多选',
             'Saved' : '已保存',
             'HandleMode' : '处理方式',
             'AnyOne' : '任何一个',
             'ParallelProcessing' : '并行处理',
             'SerialProcessing' : '串行处理',
             'ChooseHandler' : '选择处理人',
             'EffectiveCondition' : '生效条件',
             'SourceType' : '来源类型',
             'FilterIdentity' : '过滤身份',
             'Initiator' : '发起人',
             'Applicant' : '申请人',
             'BusinessRelatedPerson' : '业务相关人',
             'Department' : '部门',
             'SameWithCertainStepHandler' : '与某一步处理人相同',
             'JobCodeFilterByPerson' : '岗位代码按人过滤',
             'JobLevelFilterByPerson' : '岗位级别按人过滤',
             'JobCodeFilterByDept' : '岗位代码按部门过滤',
             'JobLevelFilterByDept' : '岗位级别按部门过滤',
             'RoleFilterByDepartment' : '角色按部门过滤',
             'RoleFilterByArea' : '角色按公司过滤',
             'DepartmentLeader' : '部门领导',
             'DirectSupervisor' : '直属主管',
             'DirectSupervisorOfPreviousStep' : '前置步骤的直属主管',
             'DepartmentLeaderOfPreviousStep' : '前置步骤的部门领导',
             'PersonOfSpecificOrganizationJobLevel' : '某组织某岗位级别的人员',
             'DirectSupervisorOfSpecificStep' : '指定步骤的直属主管',
             'DepartmentLeaderOfSpecificStep' : '指定步骤的部门领导',
             'FromOneJobLevelToAnotherJobLevel' : '从某岗位级别到某岗位级别',
             'ChooseSource' : '选择来源',
             'PleaseInputJobCodeManually' : '请手动输入岗位代码',
             'DataField' : '数据字段',
             'AccordingToTheApplicant' : '按申请人',
             'AccordingToTheField' : '按字段',
             'AccordingToTheVariable' : '按变量',
             'FilterType' : '过滤类型',
             'JobCode' : '岗位代码',
             'All' : '全部',
             'ApplicantOrganization' : '申请人组织',
             'ApplicantOrganizationAndSubordinateOrganization' : '申请人组织及下级组织',
             'CurrentApproverOrganization' : '当前审批人组织',
             'CurrentApproverOrganizationAndSubordinateOrganization' : '当前审批人组织及下级组织',
             'SpecificOrganization' : '特定组织',
             'SpecificOrganizationVariable' : '特定组织（变量）',
             'SpecificOrganizationDataField' : '特定组织（数据字段）',
             'SpecificOrganizationAndSubordinateOrganization' : '特定组织及下级组织',
             'SpecificOrganizationAndSubordinateOrganizationVariable' : '特定组织及下级组织（变量）',
             'SpecificOrganizationAndSubordinateOrganizationDataField' : '特定组织及下级组织（数据字段）',
             'Filter' : '过滤',
             'ConnectionInformation' : '连线信息',
             'ConnectionCondition' : '连线条件',
             'JumpWay' : '跳过方式',
             'AutoProcessing' : '自动处理',
             'Outdated' : '过时',
             'Assessment' : '考核',
             'NodeProperties' : '节点属性',
             'StoredProcedure' : '存储过程',
             'DllProgram' : 'DLL程序',
             'SqlScript' : 'SQL脚本',
             'Arrive' : '到达',
             'Identity' : '标识',
             'Editable' : '可编辑',
             'Readonly' : '只读',
             'Disabled' : '禁用',
             'Hidden' : '隐藏',
             'ControlStatus' : '控制状态',
             'IdentityCannotBeNull' : '标识不能为空!',
             'MustChooseOneNode' : '必须选择一个节点！',
             'CurrentIdentityExistsAlreadyCannotSet' : '当前标识已存在，不能设置！',
             'Page' : '页面',
             'Choose' : '选择',
             'ApplicantTelephone' : '申请人电话',
             'PostByName' : '发起人姓名',
             'PostByEmployeeNumber' : '发起人工号',
             'PostByDepartment' : '发起人部门',
             'PostByTelephone' : '发起人电话',
             'PostByEmail' : '发起人邮箱',
             'PostByInfo' : '发起人信息',
             'PostByMobileNumber' : '发起人手机',
             'PostByDirectManager' : '直属主管',
             'InitiatorName' : '发起人姓名',
             'InitiatorEmployeeNumber' : '发起人工号',
             'InitiatorDepartment' : '发起人部门',
             'InitiatorContactNumber' : '发起人电话',
             'InitiatorEmail' : '发起人邮箱',
             'InitiatorInfo' : '发起人信息',
             'InitiatorMobileNumber' : '发起人手机',
             'InitiatorDirectManager' : '发起人主管',
             'ApplicantName' : '申请人姓名',
             'ApplicantEmployeeNumber' : '申请人工号',
             'ApplicantDepartment' : '申请人部门',
             'ApplicantEmail' : '申请人邮箱',
             'ApplicantContactNumber' : '申请人座机',
             'ApplicantMobileNumber' : '申请人手机',
             'ApplicantDirectManager' : '申请人主管',
             'ApplicantInfo' : '申请人信息',
             'ApplicationInfo' : '申请信息',
             'SnFormat' : '流水号',
             'SelectCompany' : '启用抬头',
             'CompanyList' : '公司列表',
             'Query' : '查询',
             'LinkedWorkflow' : '绑定流程',
             'Associate' : '关联',
             'Add' : '添加',
             'PleaseEnterTheQueryCondition' : '请输入查询条件',
             'NextProcessor' : '下一步处理人',
             'ValidateData' : '验证数据',
             'ErrorMessage' : '错误信息',
             'InfoMessage' : '提示信息',
             'DataImport' : '数据导入',
             'TemplateDownload' : '下载模板',
             'Export' : '导出',
             'ExpenseReimbursementList' : '礼品费报销列表',
             'Attachment' : '附件',
             'UploadAttachment' : '上传附件',
             'Upload' : '上传',
             'NewAdd' : '新增  ',
             'Memo' : '审批意见  ',
             'ApprovalRecord' : '审批记录',
             'Approval' : '审批',
             'ExpenseSource' : '费用出处',
             'ReimbursementAmount' : '报销金额',
             'ApplicationTime' : '申请时间',
             'PurchaseType' : '采购种类（大类）',
             'PurchaseSubType' : '采购种类（小类）',
             'Supplier' : '供应商',
             'DealMoney' : '成交金额',
             'InquiryMoney' : '询价金额',
             'ProxyFor' : '代',
             'Project' : '项目',
             'UsedInCompany' : '所属公司',
             'ReportCenter' : '报表中心',
             'InfoOverview' : '信息总览',
             'WfOverview' : '流程总览',
             'WfnInfo' : '流程节点信息',
             'UserWfInfo' : '用户参与单子信息',
             'WfProcess' : '流程进度查看',
             'StandardProcessingTimeSetting' : '标准处理时间设置',
}
     mabp.localization['Bpm.en'] = {
             'AppName' : 'DFYF - workflow system',
             'SiteName' : 'DFYF',
             'PersonalInformation' : 'Personal Information',
             'AutomaticGenerationSystem' : 'Automatic generation system',
             'RealName' : 'Name',
             'BasicSettings' : 'Basic Settings',
             'NickName' : 'Nick Name',
             'ChangePassword' : 'Password',
             'Account' : 'Account',
             'OpenApi' : 'Open API',
             'Address' : 'Address',
             'Language' : 'Language',
             'Save' : 'Save',
             'Saveing' : 'Saveing',
             'OrignalPassword' : 'Orignal Password',
             'NewPassword' : 'New Password',
             'RepeatPassword' : 'Repeat Password',
             'CurrentCellphone' : 'Current Phone',
             'NewCellphone' : 'New Cellphone',
             'CurrentEmail' : 'Current Email',
             'UserAccessId' : 'User AccessId',
             'EnterpriseAccessId' : 'Enterprise AccessId',
             'UnbindAtLeastHaveOne' : 'Cellhone and email at least must have one for account using.',
             'Reset' : 'Reset',
             'ValidationCode' : 'Validation Code',
             'Cancel' : 'Cancel',
             'BindNewEmail' : 'Bind New Email',
             'BindNewCellphone' : 'Bind New Cellphone',
             'UnBind' : 'Unbind',
             'SendValidationCode' : 'Send Validation Code',
             'EnterNewEmail' : 'Enter New Email',
             'EnterNewCellphone' : 'Enter New Cellphone',
             'EnterValidationCode' : 'Enter Validation Code',
             'ChangeMail' : 'Change Email',
             'ChangeCellphone' : 'Change Cellphone',
             'BindEmail' : 'Bind Email',
             'BindCellPhone' : 'Bind Cellphone',
             'SureForBind' : 'Sure',
             'Cellphone' : 'Cellphone',
             'JobNumber' : 'JobNumber',
             'LoginAccount' : 'Login Account',
             'NotBind' : 'NotBind',
             'PleaseInputValidationCode' : 'Please Input Validation Code',
             'PleaseInputNewCellphone' : 'Please Input New Cellphone',
             'UpdateSuccessfully' : 'Update Successfully',
             'PleaseClickSendValidationCode' : 'Please click send validation code!',
             'PleaseInputNewEmail' : 'Please input new email!',
             'ValidationCodeSendedPleaseCheckCellphone' : 'Validation code sended, please check cellphone！',
             'ValidationCodeSendedPleaseCheckEmail' : 'Validation code sended, please check email！',
             'ModifyPassword' : 'Modify Password',
             'InputAccountPassword' : 'Input Account Password',
             'ConfirmThatYouAreOperatingPleaseEnterTheCurrentAccountPasswordAndContinue' : 'To confirm that you are operating, please enter the current account password and continue',
             'InputCurrentAccountPassword' : 'Input Current Account Password',
             'ConfirmAndContinue' : 'Confirm and continue',
             'AddApply' : '+ Application Agent',
             'AddAgent' : '+ Approver Agent',
             'AgentType' : 'Agent Type',
             'UseUser' : 'All Jobs',
             'UseJob' : 'Single Job',
             'NoAgentYetClickUpperRightToCreate' : 'No agent yet!',
             'AgentList' : 'Agent List',
             'WorkflowMainCategory' : 'Workflow Category',
             'WorkflowName' : 'Workflow Name',
             'FirstAgent' : 'First Agent',
             'SecondAgent' : 'Second Agent',
             'StartDate' : 'Start Date',
             'EndDate' : 'End Date',
             'WhetherValid' : 'Whether Valid',
             'Operation' : 'Operation',
             'Valid' : 'Valid',
             'Invalid' : 'Invalid',
             'Edit' : 'Edit',
             'Create' : 'Create',
             'Agent' : 'Agent',
             'Basic' : 'Basic',
             'OperationSucceeded' : 'Operation Succeeded',
             'ApplyToDatabase' : 'Applay To Database',
             'GetLatest' : 'Get Latest',
             'GetLatestWorkflow' : 'Get Latest Workflow',
             'NoWorkflowYetClickUpperRightToGetLatest' : 'No workflow yet, click upper right button to get latest!',
             'Workflow' : 'Workflow',
             'Name' : 'Name',
             'Code' : 'Code',
             'CreationDate' : 'Creation Date',
             'CreationTime' : 'Creation Time',
             'Source' : 'Source',
             'Size' : 'Size',
             'CompletionTime' : 'Completion Time',
             'SureForDeleteThisWorkflow' : 'SureForDeleteThisWorkflow?',
             'CreateWorkflow' : '+Create Workflow',
             'NoWorkflowCategoryYetPleaseCreateFirstly' : 'No workflow category yet, please create firstly',
             'WorkflowCode' : 'Workflow Code',
             'Category' : 'Category',
             'Description' : 'Description',
             'WorkflowDescription' : 'Workflow Description',
             'Close' : 'Close',
             'WorkflowInfo' : 'Workflow Info',
             'State' : 'State',
             'GetChoosedWorkflow' : 'Get Choosed Workflow',
             'SynchronizedSuccess' : 'Synchronized Success',
             'Permissions' : '的Permissions',
             'Handler' : 'Handler',
             'Launch' : 'Launch',
             'Check' : 'Check',
             'Dispatch' : 'Dispatch',
             'Delete' : 'Delete',
             'Revoke' : 'Revoke',
             'Job' : 'Job',
             'Variable' : 'Variable',
             'VariableName' : 'Variable Name',
             'VariableType' : 'Variable Type',
             'System' : 'System',
             'Refresh' : 'Refresh',
             'File' : 'File',
             'Date' : 'Date',
             'Text' : 'Text',
             'Number' : 'Number',
             'PleaseConfirmTheDeletionAgain' : 'Please confirm the deletion again?',
             'PleaseInputVariableName' : 'Please Input Variable Name',
             'DeleteSuccessfully' : 'Delete Successfully',
             'GetTableDesign' : 'Get Table Design',
             'AliasName' : 'AliasName',
             'NoTableYetClickUpperRightToGetTable' : 'No table yet, click upper right to get table!',
             'BusinessDatatable' : 'Business Datatable',
             'SysDatatable' : 'Sys Datatable',
             'Type' : 'Type',
             'ViewField' : 'View Field',
             'AssociateParentTable' : 'Associate Parent Table',
             'ChooseAssociatedParentTable' : 'Choose Associate Parent Table',
             'BasicDatatable' : 'Basic Datatable',
             'TableMaintenance' : 'Table & View Maintenance',
             'Common' : 'Common',
             'FieldCode' : 'Field Code',
             'FieldName' : 'Field Name',
             'Length' : 'Length',
             'Required' : 'Required',
             'RequirementDescription' : 'Requirement Description',
             'DataMaintenanceSettings' : 'Data Maintenance Settings',
             'WhetherVisible' : 'Whether Visible',
             'Alignment' : 'Alignment',
             'Content' : 'Content',
             'Left' : 'Left',
             'Center' : 'Center',
             'Right' : 'Right',
             'DataQuerySettings' : 'Data Query Settings',
             'CanAssociate' : 'Can Associate',
             'CanQuery' : 'Can Query',
             'CanSort' : 'Can Sort',
             'CanGroup' : 'Can Group',
             'CanStatistics' : 'Can Statistics',
             'DatatableInfo' : 'Datatable Info',
             'TableName' : 'Table Name',
             'TableDescription' : 'Table Description',
             'GetAllDatatable' : 'Get All Datatable',
             'GetChoosedDatatable' : 'Get Choosed Datatable',
             'MainDatatable' : 'Main Datatable',
             'CreateCategory' : '+Create Category',
             'NoWorkflowCategoryYetClickUpperRightToCreate' : 'No workflow category yet, click upper right to create',
             'WorkflowCategory' : 'Workflow Category',
             'ViewWorkflow' : 'View Workflow',
             'SureForDeleteThisCategory' : 'Sure for delete this category?',
             'WorkflowCategoryCode' : 'Workflow Category Code',
             'SysConfig' : 'System Config',
             'Permission' : 'Permission',
             'SyncServerAddress' : 'Sync Server Address',
             'EnterpriseCode' : 'Enterprise Code',
             'EnterpriseName' : 'Enterprise Name',
             'MessageCenterConfiguration' : 'Message Center Configuration',
             'MessageCenterAddress' : 'Message Center Address',
             'MessageCenterAccount' : 'Message Center Account',
             'MessageCenterPassword' : 'Message Center Password',
             'MailServerConfiguration' : 'Mail Server',
             'MailServerAddress' : 'Server Address',
             'MailServerPort' : 'Port',
             'MailServerAccount' : 'Account',
             'MailServerPassword' : 'Password',
             'MailServerSenderEmail' : 'Sender Email',
             'MailServerSenderName' : 'Sender Name',
             'MailServerIsSSL' : 'Is SSL',
             'MailServerIsOpen' : 'Is Open',
             'FileServerConfiguration' : 'File Server Configuration',
             'FileServerAddress' : 'File Server Address',
             'Username' : 'Username',
             'Password' : 'Password',
             'SaveSuccessfully' : 'Save Successfully',
             'Menu_My_Outing' : 'Menu_My_Outing',
             'Menu_My_Setting' : 'Menu_My_Setting',
             'Menu_My_Outing_NewApproval' : 'Menu_My_Outing_NewApproval',
             'Menu_My_Outing_NewApply' : 'Menu_My_Outing_NewApply',
             'Menu_My_WorkflowCenter_AdvanceSearch' : 'Menu_My_WorkflowCenter_AdvanceSearch',
             'Menu_My' : 'Menu_My',
             'Menu_My_Workplace' : 'Menu_My_Workplace',
             'Menu_My_WorkflowCenter' : 'Menu_My_WorkflowCenter',
             'Menu_My_DataMaintanance' : 'Menu_My_DataMaintanance',
             'Menu_My_Report' : 'Menu_My_Report',
             'Menu_Sys' : 'Menu_Sys',
             'Menu_Sys_Workflow' : 'Menu_Sys_Workflow',
             'Menu_Sys_TableAndView' : 'Menu_Sys_TableAndView',
             'Menu_Sys_Page' : 'Menu_Sys_Page',
             'Menu_Sys_Module' : 'Menu_Sys_Module',
             'Menu_Sys_Configuration' : 'Menu_Sys_Configuration',
             'Menu_Sys_Permission' : 'Menu_Sys_Permission',
             'Menu_Sys_Developer' : 'Menu_Sys_Developer',
             'SysModule_Data' : 'SysModule_Data',
             'SysModule_Data_User' : 'SysModule_Data_User',
             'SysModule_Data_Group' : 'SysModule_Data_Group',
             'SysModule_Data_Enum' : 'SysModule_Data_Enum',
             'SysModule_Data_Role' : 'SysModule_Data_Role',
             'SysModule_Data_Interface' : 'SysModule_Data_Interface',
             'SysModule_Data_BasicData' : 'SysModule_Data_BasicData',
             'SysModule_Data_GroupExtension' : 'SysModule_Data_GroupExtension',
             'Menu_My_File' : 'Menu_My_File',
             'ShowAllStep' : 'Show all',
             'Hide' : 'Hide',
             'GetLatestForm' : 'Get Latest Page',
             'NoFormYetClickUpperRightToGetLatest' : 'No Page yet, click upper right to get latest',
             'Form' : 'Page',
             'SureForDeleteThisForm' : 'Sure for delete this Page?',
             'BusinessTable' : 'Business Table',
             'FormType' : 'Page Type',
             'FormName' : 'Page Name',
             'FormDescription' : 'Page Description',
             'BasicData' : 'Basic Data',
             'Report' : 'Report',
             'FormInfo' : 'Page Info',
             'GetAllForm' : 'Get All Page',
             'GetChoosedForm' : 'Get Choosed Page',
             'EntryDetailForm' : 'Entry Detail Page',
             'MainPage' : 'Main Page',
             'FormMultiLanguageConfig' : 'Page Multi Language Config',
             'FormMultiLanguageImport' : 'Page Multi Language Import',
             'CreateModule' : '+Create Module',
             'NoModuleYetClickUpperRightToCreate' : 'No module yet, click upper right to create!',
             'IdentificationName' : 'Identification Name',
             'Open' : 'Open',
             'AssociatePage' : 'Associate Page',
             'AssociateWorkflow' : 'Associate Workflow',
             'OpenSuccessfully' : 'Open Successfully',
             'CloseSuccessfully' : 'Close Successfully',
             'Module' : 'Module',
             'IdentifierPrefix' : 'Identifier Prefix',
             'Advance' : 'Advance',
             'ModuleAssociateForm' : 'Module Associate Page',
             'PageName' : 'Page Name',
             'PageDescription' : 'Page Description',
             'FileName' : 'File Name',
             'Datatable' : 'Data Table',
             'SureForDelete' : 'Sure For Delete?',
             'SureSetStartPage' : 'Sure Set Start Page?',
             'ChooseForm' : 'Choose Page',
             'ModuleAssociateWorkflow' : 'Module Associate Workflow',
             'SwitchWorkflow' : 'Switch Workflow',
             'ConfirmSubmitWillCoverSettedForm' : 'Confirm submit will cover setted Page',
             'AssociateRight' : 'Module Rights',
             'Allow' : 'Allow',
             'OpenType' : 'Open Type',
             'ModuleOpenType' : 'Module Open Type',
             'CreateReport' : '+Create Report',
             'NoReportYetClickUpperRightToAdd' : 'No report yet, click upper right to add!',
             'DesignReportFormat' : 'Design report format',
             'ReportType' : 'Report Type',
             'DropdownlistChoose' : 'DropdownlistChoose：fix format/chart format/two-dimensional table format',
             'ReportName' : 'Report Name',
             'ReportDescription' : 'Report Description',
             'AssociateParentReport' : 'Associate Parent Report',
             'PopupSelectionReport' : 'Popup Selection Report',
             'CautionDeleteWorkflowWillDeleteAllTheRelatedData' : 'Caution! Delete workflow will delete all the related data！',
             'FixFormatReportDesign' : 'Fix Format Report Design',
             'CreateDataView' : '+Create DataView',
             'NoDataViewYetClickUpperRightToCreate' : 'No dataView yet, click upper right to create!',
             'DataView' : 'DataView',
             'DataViewCode' : 'DataView Code',
             'DataViewNameInDatatable' : 'DataView name in datatable',
             'DataViewName' : 'DataView Name',
             'DataViewDescription' : 'DataView Description',
             'DataViewSQL' : 'DataView SQL',
             'SureForDeleteThisDataView' : 'Sure for delete this dataView?',
             'DataViewFieldPropertySettings' : 'DataView field property settings',
             'DataViewSearchSQL' : 'DataView Search SQL',
             'WorkflowProcessorChange' : 'Workflow Processor Change',
             'WorkflowIntegration' : 'Workflow Integration',
             'AddWorkflowIntegration' : '+Add Integration',
             'IntegrationCode' : 'Integration Code',
             'IntegrationDescription' : 'Integration Description',
             'IntegrationMode' : 'Integration Mode',
             'IntegrationModify' : 'Modify',
             'IntegrationConfig' : 'Config',
             'IntegrationMapping' : 'Mapping',
             'IntegrationCond' : 'Condition',
             'InterfaceConfiguration' : 'Interface Configuration',
             'HandleType' : 'Handle Type',
             'FileFormat' : 'File Format',
             'LoopType' : 'Loop Type',
             'ExecutionDate' : 'Execution Date',
             'IntervalTimeMS' : 'Interval time (MS)',
             'CallbackMethod' : 'Callback Method',
             'AssociateDatatable' : 'Associate Datatable',
             'ChooseAssociatedDatatable' : 'Choose Associated Datatable',
             'Enable' : 'Enable',
             'EnableDate' : 'Enable Date',
             'Interface' : 'Interface',
             'NoServerInterfaceYetClickUpperRightToAdd' : 'No server interface yet, click upper right to add!',
             'ServerConfiguration' : 'Server Configuration',
             'ServerAddress' : 'Server Address',
             'DeleteInterfaceSuccessfully' : 'Delete interface successfully',
             'InterfaceFieldConfiguration' : 'Interface field configuration',
             'PrimaryKey' : 'Primary Key',
             'WhetherEnable' : 'Whether Enable',
             'ResetWillDeleteCurrentFiledConfigurationAreYouSure' : 'After reset, current field configuration will be deleted.  Are you sure?',
             'ftpAddress' : 'ftp Address',
             'TotalQuantity' : 'Total Quantity',
             'Increment' : 'Increment',
             'FixedTimePerDay' : 'Fixed time per day',
             'FixedTimeInterval' : 'Fixed time interval',
             'FixedTimeOfWorkingDay' : 'Fixed time of working day',
             'FixedTimeIntervalOfWorkingDay' : 'Fixed time interval of working day',
             'FileServerType' : 'File Server Type',
             'IntegrationFileServerAddress' : 'File Server Address',
             'FileServerAccount' : 'Account',
             'FileServerPassword' : 'Password',
             'FileServerPort' : 'Port',
             'FileServerFolder' : 'Folder',
             'FileContentMapping' : 'File Title Mapping',
             'FileNameFormat' : 'File Name Format',
             'FileExtension' : 'Extension',
             'SourceIdentifier' : 'Source Identifier',
             'Downloads' : 'Downloads',
             'WaitingDownload' : 'Waiting for download',
             'Download' : 'Download',
             'DataBaseServerType' : 'DataBase Server Type',
             'DataBaseServerAddress' : 'Server Address',
             'DataBaseAccount' : 'Account',
             'DataBasePassword' : 'Password',
             'DataBaseTableName' : 'Table Name',
             'DataBaseFieldMapping' : 'Field Mapping',
             'WebServiceUrl' : 'WebService Url',
             'WebServiceAccount' : 'Account',
             'WebServicePassword' : 'Password',
             'WebServiceRootName' : 'Root Element',
             'WebServiceElementMapping' : 'Element Mapping',
             'UploadIntegrationFile' : 'Upload Integration File',
             'RereadWebservice' : 'Read Url',
             'SourceTable' : 'Source Table Name',
             'SourceField' : 'Source Table Field',
             'DestElement' : 'Destination Field',
             'ParentDestElement' : 'Destination Higher Field',
             'MappingMemo' : 'Memo',
             'Undefined' : 'Undefined',
             'Mine' : 'Mine',
             'Dashboard' : 'Dashboard',
             'WorkflowCenter' : 'Workflow Center',
             'DataMaintenance' : 'Data Maintenance',
             'DataReport' : 'Data Report',
             'WorkflowConfiguration' : 'Workflow Configuration',
             'DatatableConfiguration' : 'Datatable Configuration',
             'DataViewConfiguration' : 'DataView Configuration',
             'ReportConfiguration' : 'Report Configuration',
             'FormConfiguration' : 'Page Configuration',
             'Configuration' : 'Configuration',
             'PersonalSettings' : 'Personal Settings',
             'OutSettings' : 'Out Settings',
             'Logout' : 'Logout',
             'Developer' : 'Developer',
             'TaskStatus_0' : 'Approving',
             'TaskStatus_1' : 'Completed',
             'TaskStatus_7' : 'Rejected',
             'TaskNumber' : 'Task Number',
             'Topic' : 'Topic',
             'Sn' : 'Sn',
             'Creator' : 'Creator',
             'AnAgent' : 'Agent',
             'Authorizer' : 'Authorizer',
             'UnReceived' : 'UnReceived',
             'ReceiveDate' : 'Receive Date',
             'TaskFinishStatus' : 'Completed',
             'TaskCanceled' : 'Canceled',
             'Approving' : 'Approving',
             'TaskRejectStatus' : 'Rejected',
             'PendingPurchase' : 'Pending Purchase',
             'AlreadyPurchase' : 'Already Purchase',
             'Refused' : 'Refused',
             'WorkflowType' : 'Workflow Type',
             'Company' : 'Company',
             'CC' : 'CC',
             'CCDate' : 'CC Date',
             'CurrentStatus' : 'Current Status',
             'CurrentNode' : 'Current Node',
             'CurrentHandler' : 'Current Handler',
             'ModificationDate' : 'Modification Date',
             'ProcessingNode' : 'Processing Node',
             'OtherHandler' : 'Other Handler',
             'CommonWorkflow' : 'Common Workflow',
             'CollectionWorkflow' : 'Collection Workflow',
             'AddToCommonWorkflowSuccessfullyUpToMax' : 'Add to common workflow successfully, up to max!',
             'AddToCommonWorkflowSuccessfully' : 'Add to common workflow successfully',
             'RemoveFromCommonWorkflowSuccessfully' : 'Remove from common workflow successfully',
             'WorkflowHandle' : 'Workflow Handle',
             'Count' : 'Count',
             'Clear' : 'Clear',
             'WfBusinessData' : 'Business Data',
             'LaunchWorkflow' : 'New',
             'MyPendingHandleWf' : 'Processed',
             'MyPendingReadWf' : 'Assigned',
             'WfSearch' : 'My Task',
             'MyMarkedWf' : 'Marked',
             'MyDraftWf' : 'Drafts',
             'MyRaisedWf' : 'Submitted',
             'MyHanldeWf' : 'My Handled',
             'MyWaitingWf' : 'My Waited',
             'CopyMeWf' : 'In Copy',
             'MyAuthorizedWf' : 'Authorized',
             'MyDelegateWf' : 'Delegated',
             'WfAdvancedSearch' : 'Advanced Search',
             'NewWindow' : 'New Window',
             'Embedded' : 'Embedded Window',
             'Inherit' : 'Inherit',
             'NoProcess' : 'NO Addition Workflow',
             'JumpWorkflowCenter' : 'Click and jump to Workflow Center',
             'ClickRightCorner' : 'Click ☆ on the top right corner',
             'Notasks' : 'No tasks to be processed',
             'Initiated' : 'Initiated',
             'more' : 'more',
             'Nolaunchtask' : 'No launch task',
             'NewTask' : 'Initiate a new task',
             'TaskApproval' : 'Task Approval',
             'QueryCriteria' : 'Approval record',
             'Search' : 'Search',
             'SelectTask' : 'Select Task',
             'Notaskwating' : 'There is no waited process',
             'NoMarked' : 'There is no marked process',
             'NoDraft' : 'There is no draft process',
             'Nohandled' : 'There is no handled process',
             'NoWaited' : 'There is no waited process',
             'NoCopied' : 'There is no copied process',
             'NoAuthorized' : 'There is no authorized process',
             'NoDelegated' : 'There is no delegated process',
             'EnumCollection' : 'Enum Collection',
             'EnumKey' : 'Enum Key',
             'EnumValue' : 'Enum Value',
             'AddCreate' : '+Create',
             'PleaseInputName' : 'Please Input Name',
             'Value' : 'Value',
             'GroupLevel' : 'Group Level',
             'GroupType' : 'Group Type',
             'JobLevel' : 'Job Level',
             'JobLevel>=' : 'Job Level >=',
             'JobLevel<=' : 'Job Level <=',
             'JobLevel=' : 'Job Level =',
             'NameCannotBeNull' : 'Name cannot be null',
             'ValueCannotBeNull' : 'Value cannot be null',
             'GroupStructure' : 'Group Structure',
             'BindSuccessfully' : 'Bind Successfully',
             'UnBindSuccessfully' : 'UnBind Successfully',
             'Group' : 'Group',
             'ChineseName' : 'Chinese Name',
             'EnglishName' : 'English Name',
             'JobBindGroup' : 'Job Bind Group',
             'BindGroup' : 'Bind Group',
             'PleaseChooseGroup' : 'Please Choose Group',
             'Confirm' : 'Confirm',
             'TransferJob' : 'Transfer Job',
             'To' : 'To',
             'JobUser' : 'Job User',
             'ChooseOneJobAtLeast' : 'Choose one job at least',
             'WhetherToMoveTheChildJobTogether' : 'Whether to move the child job together。Click Cancel to move only the current job.',
             'JobChange' : 'Job Change',
             'ChildGroup' : 'Child Group',
             'GroupName' : 'Group Name',
             'GroupCode' : 'Group Code',
             'CancelGroupAndTransforToJob' : 'Cancel group and transfor to job',
             'TransforToJob' : 'Transfor to job',
             'TransforToJobGroupWillBeDeletedJobKeep' : 'Transfor to job, group will be deleted, job keep',
             'DeleteThisJobAndGroupWillBeDeleted' : 'After delete this job, group will be deleted at the same time.',
             'IfWannaRemovingBindBetweenGroupAndJobGoToGroupChart' : 'If you wanna removing the binding between group and job, please go to group chart.',
             'UnBindFunction' : '[UnBind]Function',
             'JobName' : 'Job Name',
             'User' : 'User',
             'JobTransforToGroup' : 'Job transfor to group',
             'TransforToGroup' : 'Transfor to group',
             'DeleteThisJobIfChildNodeExistThenCannotDelete' : 'Delete this job, if child node exists then cannot delete it.',
             'PleaseInputNewGroupName' : 'Please input new group name',
             'DisplayOrder' : 'Display Order',
             'MultipleLanguageConfiguration' : 'Multiple Language Configuration',
             'DeleteUserSuccessfully' : 'Delete user successfully',
             'SystemEnumeration' : 'System Enumeration',
             'InterfaceConfig' : 'Interface Config',
             'BasicDataConfig' : 'Data Config',
             'BasicDataImport' : 'Basic Data Import',
             'Role' : 'Role',
             'RoleJob' : 'Role job',
             'RootRole' : 'Root Role',
             'ChooseARoleFirstly' : 'Choose a role firstly',
             'RoleJobArea' : 'Choose area',
             'RoleJobMemo' : 'Memo',
             'AddUser' : 'Add User',
             'NoUserYetClickUpperRightToAdd' : 'No user yet, click upper right to add',
             'EnterpriseUser' : 'Enterprise User',
             'Email' : 'Email',
             'GroupExtension' : 'GroupExtension',
             'GroupExtensionCompany' : 'Company',
             'AreaCode' : 'AreaCode',
             'Fax' : 'Fax',
             'GroupExtensionMemo' : 'Memo',
             'FilterCondition' : 'Filter Condition',
             'ShaluWorkflowDesigner' : 'Shalu Workflow Designer',
             'AllChangesHaveBeenSaved' : 'All changes have been saved',
             'SavingData' : 'Saving Data...',
             'accessCondition' : 'Access Condition',
             'Button' : 'Button',
             'CorrespondingEvent' : 'Corresponding Event',
             'JumpNode' : 'Jump Node',
             'SetVariable' : 'Set Variable',
             'Action' : 'Action',
             'StateHasBeenSaved' : 'State has been saved',
             'EndNode_EventCompleted' : 'Complete',
             'EndNode_EventRejected' : 'Rejected',
             'EndNode_EventCanceled' : 'Canceled',
             'MultiLanguageHasBeenSaved' : 'Multi language has been saved',
             'CommandType' : 'Command Type',
             'CommandText' : 'Command Text',
             'CCTarget' : 'CC Target',
             'EnableCheck' : 'Enable Check',
             'StandardProcessingTime' : 'Standard processing time',
             'NodeCode' : 'Node Code',
             'PleaseInputNodeCode' : 'Please input node code',
             'NodeName' : 'Node Name',
             'NodeDescription' : 'Node Description',
             'PleaseInputNodeDescription' : 'Please input node description',
             'Mode' : 'Mode',
             'TheRecipient' : 'The Recipient',
             'Format' : 'Format',
             'Notice' : 'Notice',
             'PleaseChooseTheFollowingJumpWay' : 'Please choose the following jump way',
             'HandlerSameWithSubmitterThenSkip' : 'Handler same with submitter then skip',
             'SameWithPreviousNodeHandlerThenSkip' : 'Same with previous node handler then skip',
             'SameWithCertainNodeHandlerThenSkip' : 'Same with certain node handler then skip',
             'PleaseChoose' : 'Please Choose',
             'SameWithAnyPreviousNodeHandlerThenSkip' : 'Same with any previous node handler then skip',
             'NoNodeHandlerThenSkip' : 'No node handler then skip',
             'OutdatedNotice' : 'Outdated Notice',
             'HourStartEvery' : 'Hour start, every',
             'Hour' : 'Hour',
             'SendNotificationToFollowingPerson' : 'Send notification to following person',
             'OutdatedHandle' : 'Outdated Handle',
             'Exceed' : 'Exceed',
             'HourLater' : 'hour later',
             'AutomaticallyToTheNextStep' : 'Automatically to the next step',
             'AutomaticTransferLeadership' : 'Automatic transfer leadership',
             'FixedOptions' : 'Fixed Options',
             'PretreatmentPerson' : 'Pretreatment Person',
             'SingleSelect' : 'Single Select',
             'MultiSelect' : 'Multi Select',
             'Saved' : 'Saved',
             'HandleMode' : 'Handle Mode',
             'AnyOne' : 'Any One',
             'ParallelProcessing' : 'Parallel Processing',
             'SerialProcessing' : 'Serial Processing',
             'ChooseHandler' : 'Choose Handler',
             'EffectiveCondition' : 'Effective Condition',
             'SourceType' : 'Source Type',
             'FilterIdentity' : 'Filter Identity',
             'Initiator' : 'Initiator',
             'Applicant' : 'Applicant',
             'BusinessRelatedPerson' : 'Business related person',
             'Department' : 'Department',
             'SameWithCertainStepHandler' : 'Same with certain step handler',
             'JobCodeFilterByPerson' : 'Job code filter by person',
             'JobLevelFilterByPerson' : 'Job level filter by person',
             'JobCodeFilterByDept' : 'Job code filter by department',
             'JobLevelFilterByDept' : 'Job level filter by department',
             'RoleFilterByDepartment' : 'Role filter by department',
             'RoleFilterByArea' : 'Role filter by area',
             'DepartmentLeader' : 'Department Leader',
             'DirectSupervisor' : 'Direct Supervisor',
             'DirectSupervisorOfPreviousStep' : 'Direct supervisor of previous step',
             'DepartmentLeaderOfPreviousStep' : 'Department leader of previous step',
             'PersonOfSpecificOrganizationJobLevel' : 'Person of specific organization job level',
             'DirectSupervisorOfSpecificStep' : 'Direct supervisor of specific step',
             'DepartmentLeaderOfSpecificStep' : 'Department leader of specific step',
             'FromOneJobLevelToAnotherJobLevel' : 'From one job level to another job level',
             'ChooseSource' : 'Choose Source',
             'PleaseInputJobCodeManually' : 'Please input job code manually',
             'DataField' : 'Data Field',
             'AccordingToTheApplicant' : 'According to the applicant',
             'AccordingToTheField' : 'According to the field',
             'AccordingToTheVariable' : 'According to the variable',
             'FilterType' : 'Filter Type',
             'JobCode' : 'Job Code',
             'All' : 'All',
             'ApplicantOrganization' : 'Applicant Organization',
             'ApplicantOrganizationAndSubordinateOrganization' : 'Applicant organization and subordinate organization',
             'CurrentApproverOrganization' : 'Current approver organization',
             'CurrentApproverOrganizationAndSubordinateOrganization' : 'Current approver organization and subordinate organization',
             'SpecificOrganization' : 'Specific Organization',
             'SpecificOrganizationVariable' : 'Specific Organization(Variable)',
             'SpecificOrganizationDataField' : 'Specific Organization(Data Field)',
             'SpecificOrganizationAndSubordinateOrganization' : 'Specific organization and subordinate organization',
             'SpecificOrganizationAndSubordinateOrganizationVariable' : 'Specific organization and subordinate organization(Variable)',
             'SpecificOrganizationAndSubordinateOrganizationDataField' : 'Specific organization and subordinate organization(Data Field)',
             'Filter' : 'Filter',
             'ConnectionInformation' : 'Connection Information',
             'ConnectionCondition' : 'Connection Condition',
             'JumpWay' : 'Jump Way',
             'AutoProcessing' : 'Auto Processing',
             'Outdated' : 'Outdated',
             'Assessment' : 'Assessment',
             'NodeProperties' : 'Node Properties',
             'StoredProcedure' : 'Stored Procedure',
             'DllProgram' : 'Dll Program',
             'SqlScript' : 'SQL Script',
             'Arrive' : 'Arrive',
             'Identity' : 'Identity',
             'Editable' : 'Editable',
             'Readonly' : 'Readonly',
             'Disabled' : 'Disabled',
             'Hidden' : 'Hidden',
             'ControlStatus' : 'Control Status',
             'IdentityCannotBeNull' : 'Identity cannot be null!',
             'MustChooseOneNode' : 'Must choose one node！',
             'CurrentIdentityExistsAlreadyCannotSet' : 'Current identity exists already, cannot set！',
             'Page' : 'Page',
             'Choose' : 'Choose',
             'ApplicantTelephone' : 'Applicant Telephone',
             'PostByName' : 'Post By Name',
             'PostByEmployeeNumber' : 'Post By Employee Number',
             'PostByDepartment' : 'Post By Department',
             'PostByTelephone' : 'Post By Telephone',
             'PostByEmail' : 'Post By Email',
             'PostByInfo' : 'Post By Info',
             'PostByMobileNumber' : 'Post By Mobile',
             'PostByDirectManager' : 'Post By Direct Manager',
             'InitiatorName' : 'Initiator Name',
             'InitiatorEmployeeNumber' : 'Initiator Employee No.',
             'InitiatorDepartment' : 'Initiator Department',
             'InitiatorContactNumber' : 'Initiator Contact No.',
             'InitiatorEmail' : 'Initiator Email',
             'InitiatorInfo' : 'Initiator Information',
             'InitiatorMobileNumber' : 'Initiator Mobile No.',
             'InitiatorDirectManager' : 'Initiator Direct Manager',
             'ApplicantName' : 'Applicant Name',
             'ApplicantEmployeeNumber' : 'Applicant Employee No.',
             'ApplicantDepartment' : 'Applicant Department',
             'ApplicantEmail' : 'Applicant Email',
             'ApplicantContactNumber' : 'Applicant Landline',
             'ApplicantMobileNumber' : 'Applicant Mobile No',
             'ApplicantDirectManager' : 'Applicant Direct Manager',
             'ApplicantInfo' : 'Applicant Information',
             'ApplicationInfo' : 'Application Info',
             'SnFormat' : 'Sn Format',
             'SelectCompany' : 'Use Company',
             'CompanyList' : 'Company List',
             'Query' : 'Query',
             'Associate' : 'Associate',
             'LinkedWorkflow' : 'Linked Workflow',
             'Add' : 'Add',
             'PleaseEnterTheQueryCondition' : 'Please enter the query condition',
             'NextProcessor' : 'Next Processor',
             'ValidateData' : 'Validate Data',
             'ErrorMessage' : 'Error Message',
             'InfoMessage' : 'Info Message',
             'DataImport' : 'Data Import',
             'TemplateDownload' : 'Template Download',
             'Export' : 'Export',
             'ExpenseReimbursementList' : 'Expense Reimbursement List',
             'Attachment' : 'Attachment',
             'UploadAttachment' : 'Upload Attachment',
             'Upload' : 'Upload',
             'NewAdd' : 'Add',
             'Memo' : 'Memo',
             'ApprovalRecord' : 'Approval Record',
             'Approval' : 'Approval',
             'ExpenseSource' : 'Expense Source',
             'ReimbursementAmount' : 'Reimbursement Amount',
             'ApplicationTime' : 'Application Time',
             'PurchaseType' : 'Purchase Type',
             'PurchaseSubType' : 'Purchase SubType',
             'Supplier' : 'Supplier',
             'DealMoney' : 'Deal Money',
             'InquiryMoney' : 'Inquiry Money',
             'ProxyFor' : 'Proxy For',
             'Project' : 'Project',
             'UsedInCompany' : 'Used In Company',
             'ReportCenter' : 'Report Center',
             'InfoOverview' : 'Info Overview',
             'WfOverview' : 'Workflow Overview',
             'WfnInfo' : 'Workflow Info',
             'UserWfInfo' : 'User Wf Info',
             'WfProcess' : 'Workflow Process',
             'StandardProcessingTimeSetting' : 'Standard Processing Time Setting',
}

mabp.localization.getResouce = function(sourceName){
return mabp.localization[sourceName].texts;
}
})();
